---
title: "EDA"
author: "Jinyu Luo"
date: "2024-04-11"
output: 
  pdf_document
  word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
```

```{r Data Cleaning}
# States info that were collected in 2017-18 
state2017 <- c("Colorado", "Connecticut", "Minnesota", "Montana", 
               "New Jersey", "New York", "North Dakota", 
               "Pennsylvania", "South Dakota", "Utah", "Washington")

# State abbreviations mapping
state_abbreviations <- c(
  "Alabama"="AL", "Alaska"="AK", "Arizona"="AZ", "Arkansas"="AR", 
  "California"="CA", "Colorado"="CO", "Connecticut"="CT", "Delaware"="DE", 
  "Florida"="FL", "Georgia"="GA", "Hawaii"="HI", "Idaho"="ID", "Illinois"="IL", 
  "Indiana"="IN", "Iowa"="IA", "Kansas"="KS", "Kentucky"="KY", "Louisiana"="LA",
  "Maine"="ME", "Maryland"="MD", "Massachusetts"="MA", "Michigan"="MI",
  "Minnesota"="MN", "Mississippi"="MS", "Missouri"="MO", "Montana"="MT", 
  "Nebraska"="NE", "Nevada"="NV", "New Hampshire"="NH", "New Jersey"="NJ",
  "New Mexico"="NM", "New York"="NY", "North Carolina"="NC", "North Dakota"="ND",
  "Ohio"="OH","Oklahoma"="OK", "Oregon"="OR", "Pennsylvania"="PA", "Rhode Island"="RI", 
  "South Carolina"="SC","South Dakota"="SD", "Tennessee"="TN", "Texas"="TX", 
  "Utah"="UT", "Vermont"="VT","Virginia"="VA", "Washington"="WA", "West Virginia"="WV",
  "Wisconsin"="WI", "Wyoming"="WY"
)

vaccine <- read.csv("vaccine.csv") %>% 
  mutate(type = case_when(type == ""~"Unknown", 
                          type %in% c("BOCES", "Kindergarten", "Nonpublic") ~ "Others",
                          TRUE ~ type), 
         mmr = ifelse(mmr == -1, NA, mmr), 
         overall = ifelse(overall == -1, NA, overall), 
         per_capita = statespending2016/schagepop2016, 
         year = case_when(state %in% state2017 ~ "2017-18", TRUE ~ "2018-19"),
         county = ifelse(county == "", NA, county), 
         city = ifelse(city == "", NA, city),
         state_abbr = state_abbreviations[state])

obsID <- 1:nrow(vaccine)
vac <- vaccine %>% mutate(oID = obsID) %>% relocate(oID, .before =state)
duplicate_df <- vac %>% 
  group_by(state, county, city, name) %>% 
  reframe(oID = oID, type = type, year = year, n= n(), 
          enroll = enroll, mmr = mmr, overall = overall) %>% 
  filter(n > 1) %>% 
  group_by(state, county, city, name) %>% 
  mutate(record = row_number()) %>% ungroup()

# Calculate average of duplicated data 
avg_duplicates <- duplicate_df %>%
  group_by(state, county, city, name) %>% 
  mutate(mean_enroll = mean(enroll), mean_mmr = mean(mmr), 
         mean_overall = mean(overall)) %>% 
  select(-c(mmr, overall, enroll, n)) %>% 
  rename(mmr = mean_mmr, overall=mean_overall, enroll = mean_enroll)

remove_sid <- avg_duplicates %>% filter(record != 1) %>% pull(oID)

data <- vac %>% filter(!(oID %in% remove_sid)) %>% 
  # Add the total number of schools in each state 
  left_join(vac %>% group_by(state) %>% 
              summarise(n_school = n_distinct(name)), by = "state")

# Separate Data
MMR <- data %>% filter(!is.na(mmr)) 
nStates <- n_distinct(MMR$state)
# Create state ID 
MMR <- MMR %>% left_join(data.frame(state = unique(MMR$state), stateID = 1:nStates))

overall <- data %>% filter(!is.na(overall)) 
nStates <- n_distinct(overall$state)
overall <- overall %>% left_join(data.frame(state = unique(MMR$state), stateID = 1:nStates))
```

## Stratified Sampling

### MMR 

```{r}
# Step 1: Calculate weights for each state based on the number of schools
state_weights <- mmr_dat %>%
  count(state) %>%
  mutate(weight = n / sum(n))

# Step 2: Sample schools within each state, proportional to state weights
# Set a total sample size of N schools
N <- 3000  # Total desired sample size

# Calculate the number of schools to sample from each state, based on weights
state_weights <- state_weights %>%
  mutate(sample_size = round(weight * N))

set.seed(123)

# mmr_samples <- mmr_dat %>%
#   group_by(state) %>%
#   sample_n(N, replace = FALSE) %>%
#   mutate(schoolID = row_number()) %>%
#   relocate(schoolID, .after = stateID) %>%
#   ungroup() %>%
#   arrange(stateID)


mmr_samples <- NULL
for (i in 1:nrow(state_weights)) {
  state <- state_weights[i, ]$state
  size <- state_weights$sample_size[i]
  sample <- mmr_dat %>% filter(state == state) %>%
    sample_n(size, replace = FALSE)
  mmr_samples <- rbind(mmr_samples, sample)
}

mmr_samples <- mmr_samples %>% group_by(state) %>%
  mutate(schoolID = row_number()) %>%
  relocate(schoolID, .after = stateID) %>%
  ungroup() %>%
  arrange(stateID)
```

```{r}
# Stratified Sampling 
# Step 1: Calculate weights for each state based on the number of schools
state_weights <- overall_dat %>%
  count(state) %>%
  mutate(weight = n / sum(n))

# Step 2: Sample schools within each state, proportional to state weights
# Set a total sample size of N schools
N <- 3000  # Total desired sample size

# Calculate the number of schools to sample from each state, based on weights
state_weights <- state_weights %>%
  mutate(sample_size = round(weight * N))

set.seed(10049)
overall_samples <- NULL
for (i in 1:nrow(state_weights)) {
  state <- state_weights[i, ]$state
  size <- state_weights$sample_size[i]
  sample <- overall_dat %>% filter(state == state) %>% 
    sample_n(size, replace = FALSE)
  overall_samples <- rbind(overall_samples, sample)
}

overall_samples <- overall_samples %>% group_by(state) %>% 
  mutate(schoolID = row_number()) %>% 
  relocate(schoolID, .after = stateID) %>% 
  ungroup() %>% 
  arrange(stateID)
```


# Best GEE for MMR 

```{r}
mmr_gee <- geeglm(mmr ~ per_capita + n_school + type, 
                    family = gaussian, 
                    data = mmr_samples, 
                    id = stateID, 
                    corstr = "exchangeable")
summary(mmr_gee)
```


# Best GEE for Overall 

```{r}
overall_gee <- geeglm(mmr ~ per_capita + n_school + type, 
                    family = gaussian, 
                    data = overall_samples, 
                    id = stateID, 
                    corstr = "ar1")
summary(overall_gee)
```