---
title: "Group E Tables"
author: "Jinyu Luo"
date: "2024-04-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
```

# MMR 

## Model Selection 

```{r}
data.frame(
  struc = c("Exchangeable", "AR1", "Independence"), 
  QIC = c(3007.5, 3015.7, 3015.8, 
          3027.8, 3046.3, 3046.6), 
  delta = c(0.00, 8.25, 8.26, 
            0.00, 18.54, 18.86), 
  weight = c(0.969, 0.016, 0.016, 
             1, 0, 0)) %>% 
  kable(booktabs = TRUE, 
        col.names = c("Structure", "QIC", "Delta", "Weight"),
        caption = "Model Selection Result for MMR Rate") %>% 
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  pack_rows("Unadjusted", 1, 3) %>% 
  pack_rows("Adjusted", 4, 6)
```



## MMR Best Model Estimation Table 

```{r}
data.frame(
  ` ` = c("Intercept", "Per Capita", "Number of Schools", 
          "Others", "Private", "Public", "Unknown"), 
  Estimate = c(84.8, 0.000376, 0.000377, 6.13, 0.432, 5.31, 3.32), 
  Std.err = c(2.06, 0.000142, 0.000279, 0.691, 1.18, 0.205,1.34),
  Wald = c(1693.9, 7.02, 1.83, 78.69, 0.13, 669.09, 6.11), 
  `P-value` = c("< 0.05", "< 0.05", "0.1757", "<0.05", 
                "0.7151", "<0.05", "0.0135")
)%>% 
  kable(booktabs = TRUE, 
        caption = "Best Model Estimation Result for MMR Vaccination Rate") %>% 
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  pack_rows("School Type", 4, 7) 
```

\newpage 

# Overall 

## Model Selection 

```{r}
data.frame(
  struc = c("Exchangeable", "Independence", "AR1"), 
  QIC = c(2934.4, 3012.3, 3012.3), 
  delta = c(0.00, 77.92, 77.94), 
  weight = c(1, 0, 0)) %>% 
  kable(booktabs = TRUE, 
        col.names = c("Structure", "QIC", "Delta", "Weight"),
        caption = "Unadjusted Model Selection Result for Overall Rate") %>% 
  kable_styling(latex_options = c("striped", "scale_down")) 
```


```{r}
data.frame(
  struc = c("AR1", "Independence", "Exchangeable"), 
  QIC = c(3062.3, 3062.4, 3065.7), 
  delta = c(0.00, 0.05, 3.34), 
  weight = c(0.462, 0.451, 0.087)) %>% 
  kable(booktabs = TRUE, 
        col.names = c("Structure", "QIC", "Delta", "Weight"),
        caption = "Adjusted Model Selection Result for Overall Rate") %>% 
  kable_styling(latex_options = c("striped", "scale_down"))
```


## Best Model Estimation Table 

```{r}
data.frame(
  ` ` = c("Intercept", "Per Capita", "Number of Schools", 
          "Private", "Public", "Unknown"), 
  Estimate = c(79.06, 0.000813, 0.00128, -4.11, -2.04, -2.96), 
  Std.err = c(4.364, 0.000496, 0.000106, 1.324, 1.260, 3.955),
  Wald = c(328.197, 2.688, 145.729, 9.642, 2.611, 0.559), 
  `P-value` = c("< 0.05", "0.101", "<0.05", "<0.05", "0.106", "0.454"))%>% 
  kable(booktabs = TRUE, 
        caption = "Best Model Estimation Result for MMR Vaccination Rate") %>% 
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  pack_rows("School Type", 4, 6) 
```
## Combination of selection of models

```{r}
results_df <- data.frame(
  Structure = c("Exchangeable", "AR1", "Independence"),
  QIC_MMR = c(3007.5, 3015.7, 3015.8, 3027.8, 3046.3, 3046.6), 
  Delta_MMR = c(0.00, 8.25, 8.26,0.00, 18.54, 18.86), 
  Weight_MMR = c(0.969, 0.016, 0.016, 1, 0, 0),
  QIC_Overall = c(2934.4, 3012.3, 3012.3,3062.3, 3062.4, 3065.7),
  Delta_Overall = c(0.00, 77.92, 77.94,0.00, 0.05, 3.34),
  Weight_Overall = c(1, 0, 0, 0.462, 0.451, 0.087)
)

# Create the table with kable and kableExtra
kable(results_df, booktabs = TRUE, longtable = TRUE,
      col.names = c("Structure", rep(c("QIC", "Delta", "Weight"),2))) %>%
  kable_styling(font_size = 4.7, latex_options = "striped", position = "center") %>%
  column_spec(1, bold = TRUE) %>%
  add_header_above(c(' '=1, "Parameter Estimates for Model with Outcome MMR" = 3, 
                     "Parameter Estimates for Model with Outcome Overall" = 3))%>%
  pack_rows("Unadjusted", 1, 3) %>%
  pack_rows("Adjusted", 4, 6)
```
